import { i18n, Locale } from '@/i18n.config';
import type { Metadata } from 'next';

import '../../../styles/globals.css';

import { Inter } from 'next/font/google';
import Footer from './components/Footer';
import Navbar from './components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'dubai french tutors',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body>
        <Navbar lang={params.lang} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
